# site properties and page defaults
title: Robot Interaction and Manipulation Lab
subtitle: School of Information Science and Technology, ShanghaiTech University
# description: We study how robot interacts with the environments and mani
# header: images/molecular.jpg
header: images/3d-robot-hand-background-ai-technology-side-view.jpg
footer: images/molecular-ai-footer.png
header-dark: true

# site social media and other links
links:
  github: RIM-Laboratory
  # twitter: papaemmanuillab
  # email: papaemme@mskcc.org
  # website: https://www.mskcc.org/research-areas/labs/elli-papaemmanuil
  # google-scholar: yQbbId0AAAAJ
  # orcid: 0000-0003-1709-8983

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
